"""Confluence和CQL特定的常量。"""

# 基于 https://developer.atlassian.com/cloud/confluence/cql-functions/#reserved-words
# 列表可能需要根据实际解析器行为进行完善
# 使用小写字母进行不区分大小写的匹配
RESERVED_CQL_WORDS = {
    "after",
    "and",
    "as",
    "avg",
    "before",
    "begin",
    "by",
    "commit",
    "contains",
    "count",
    "distinct",
    "else",
    "empty",
    "end",
    "explain",
    "from",
    "having",
    "if",
    "in",
    "inner",
    "insert",
    "into",
    "is",
    "isnull",
    "left",
    "like",
    "limit",
    "max",
    "min",
    "not",
    "null",
    "or",
    "order",
    "outer",
    "right",
    "select",
    "sum",
    "then",
    "was",
    "where",
    "update",
}

# 如果将来需要，请在此处添加其他Confluence特定的常量。
